/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemasUuidIndexRouteImport } from './routes/schemas/$uuid.index'
import { Route as SchemasUuidGroupNameRouteImport } from './routes/schemas/$uuid/$group.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasUuidIndexRoute = SchemasUuidIndexRouteImport.update({
  id: '/schemas/$uuid/',
  path: '/schemas/$uuid/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasUuidGroupNameRoute = SchemasUuidGroupNameRouteImport.update({
  id: '/schemas/$uuid/$group/$name',
  path: '/schemas/$uuid/$group/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schemas/$uuid': typeof SchemasUuidIndexRoute
  '/schemas/$uuid/$group/$name': typeof SchemasUuidGroupNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schemas/$uuid': typeof SchemasUuidIndexRoute
  '/schemas/$uuid/$group/$name': typeof SchemasUuidGroupNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schemas/$uuid/': typeof SchemasUuidIndexRoute
  '/schemas/$uuid/$group/$name': typeof SchemasUuidGroupNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schemas/$uuid' | '/schemas/$uuid/$group/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schemas/$uuid' | '/schemas/$uuid/$group/$name'
  id: '__root__' | '/' | '/schemas/$uuid/' | '/schemas/$uuid/$group/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemasUuidIndexRoute: typeof SchemasUuidIndexRoute
  SchemasUuidGroupNameRoute: typeof SchemasUuidGroupNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$uuid/': {
      id: '/schemas/$uuid/'
      path: '/schemas/$uuid'
      fullPath: '/schemas/$uuid'
      preLoaderRoute: typeof SchemasUuidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas/$uuid/$group/$name': {
      id: '/schemas/$uuid/$group/$name'
      path: '/schemas/$uuid/$group/$name'
      fullPath: '/schemas/$uuid/$group/$name'
      preLoaderRoute: typeof SchemasUuidGroupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemasUuidIndexRoute: SchemasUuidIndexRoute,
  SchemasUuidGroupNameRoute: SchemasUuidGroupNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
